### ISSUE TITLE
Couldn't install the NuGet package to UWP project

### ISSUE THREAD

**Issue by cherepets** [renber/SeafClient#1]
Log:
Restoring packages for '{ProjectName}'.
Restoring packages for c:\users\{UserName}\documents\visual studio 15\Projects\{ProjectName}\{ProjectName}\project.json...
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json 510ms
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/7.0.1/newtonsoft.json.7.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/7.0.1/newtonsoft.json.7.0.1.nupkg 518ms
Installing Newtonsoft.Json 7.0.1.
SeafClient 1.0.0 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
SeafClient 1.0.0 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
SeafClient 1.0.0 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
SeafClient 1.0.0 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
SeafClient 1.0.0 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
SeafClient 1.0.0 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
SeafClient 1.0.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for '{ProjectName}'.
Package restore failed. Rolling back package changes for '{ProjectName}'.
========== Finished ==========

**Comment by cherepets** [comment]
I've created a pull request with new nuspec file to fix that:
https://github.com/renber/SeafClient/pull/2

Would be happy if you update your package.

**Comment by renber** [comment]
Thanks. I'm going to test the client under UWP and will update the package if everything works as expected.
