### ISSUE TITLE
Character Encoding

### ISSUE THREAD

**Issue by JasonGodN** [renber/SeafClient#11]
When I upload a file with chinese file name by the follow way.

            string filename = @"D:\上传.txt"";
            FileStream fs = new FileStream(filename, FileMode.Open, FileAccess.Read);
            string name = Path.GetFileName(filename);
            var result = await Session.UploadSingle(mylib, targetDir, name, fs);

The chinese characters are not displayed properly in the server. 
Would you give me some advice, thank you very much! @renber

**Comment by renber** [comment]
After doing a bit of research this seems to be a problem of dotnet's HttpClient (it does not encode the Content-Disposition header as UTF-8). See [here](https://stackoverflow.com/questions/47004296/httpclient-wrong-encoding-in-content-disposition) for more info. 

Unfortunately, the seafile server does not seem to accept the format defined in RFC5987 (filename=?utf-8?...)
If reflection is a viable option for you, you can set the default encoding of HttpClient to UTF-8 beforehand. This will temporarily solve the issue but appears to be non-standard (as given in the stackoverflow thread):
```C#
typeof(HttpClient)
                .Assembly
                .GetType("System.Net.Http.HttpRuleParser")
                .GetField("DefaultHttpEncoding", BindingFlags.Static | BindingFlags.NonPublic)
                .SetValue(null, System.Text.Encoding.UTF8);
```

**Comment by renber** [comment]
Further tests show that this is a specific problem with how the Content-Disposition field is encoded (and that the seafile server does not support the filename* notation). One possible work-around which does not need reflection, is to upload the file with a filename which only contains ascii chars and then renaming it to the desired filename containing non-ascii chars:

```
// check if the filename contains non-ascii chars
string name = @"上传.txt";                    
String escName = Uri.EscapeDataString(name);
if (name == escName)
{
    await session.UploadSingle(defLib, "/", name, stream);
} else
{
   // generate a unique filename which contains only numbers
    String uniqueFilename = Guid.NewGuid().ToString("N");
    await session.UploadSingle(defLib, "/", uniqueFilename, stream);
   // rename the uploaded file to the actually desired name
    await session.RenameFile(defLib, "/" + uniqueFilename, name);
}      
```
