### ISSUE TITLE
CreateGroup-Request

### ISSUE THREAD

**Issue by PeterPetersen** [renber/SeafClient#12]
Hello, (yes i can  :) )

could you please help me to create the CreateGroup-Request in C#/ASP.NET?
I saw the code for other Requests, but i dont know how to call a CreateGroupRequest.

Kindly regards
Frank

**Comment by renber** [comment]
I have added ListGroupsRequests, AddGroupRequest and DeleteGroupRequests.
For the AddGroupRequest  I added support for the HTTP PUT action to SeafClient.
If you are interested you can have a look at the implementation.
I am going to implement the other group related requests as soon as possible for a potential 1.2.0 release
