### ISSUE TITLE
Support WebProxy

### ISSUE THREAD

**Issue by AKrasheninnikov** [renber/SeafClient#13]
Looks like the client has no way to specify WebProxy.

**Comment by renber** [comment]
Commit e89f59e adds a constructor to the default SeafHttpConnection to which you can pass a custom HttpClientHandler (e.g. with a set WebProxy configuration).
Of course, you can also provide a custom implementation for ISeafWebConnection which does it all internally (and probably shares most of the code with SeafHttpConnection).

Alternatively you should be able to define the proxy in your app.config / web.config file (see [here](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings))
