### ISSUE TITLE
Migrate to .net core

### ISSUE THREAD

**Issue by lukali1986** [renber/SeafClient#16]
Hello！
Whether to consider migrating the project to .net core for better compatibility and easier promotion.
@renber

**Comment by renber** [comment]
As this is a library, I am wondering if it would make more sense to target .NET Standard and keep support for Framework and Core in the same project?

**Comment by renber** [comment]
I have ported the library to support .NET Standard 1.1
With this it can be used with the following platforms:

.NET Core >= 1.0
.NET Framework >= 4.5
Mono >= 4.6
Xamarin.iOS >= 10.0
Xamarin.Mac >= 3.0
Xamarin.Android >= 7.0
UWP >= 10.0
Unity >= 2018.1
(see [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard))

**Comment by renber** [comment]
[Release 1.3](https://github.com/renber/SeafClient/releases/tag/v1.3.0) is now targeting .NET Standard 1.1
