### ISSUE TITLE
Upload request fails on UWP

### ISSUE THREAD

**Issue by cherepets** [renber/SeafClient#4]
GetRuntimeMethod with derived class as parameter returns null and method fails with NullReferenceException.
GetTypeInfo().GetDeclaredMethod should work crossplatform.
Suggested changed add to pull request.
https://github.com/renber/SeafClient/pull/2

**Comment by renber** [comment]
Thanks. I'll have to test it with Windows Phone 7, for which I want to keep compatibility, before accepting the change.
