### ISSUE TITLE
GetFileDownloadLink returns address with wrong server uri

### ISSUE THREAD

**Issue by uPloraX** [renber/SeafClient#7]
I etablish a connection with an own seafile server host on a virtual linux server (same computer).
With a private dhcp from VirtualBox I can connect by e.g. `192.168.56.100:8000` which is only available on my pc (not bridged to lan).
That works just fine, but when I get the download address from the `GetFileDownloadLink` task, it returns the correct file with a wrong server uri (`192.168.122.1:8082/files/...` instead of my custom one; default?) and obviously throws an exception.
If I check the `ServerUri` property before, it returns the correct one.

Did I miss something? Thanks in advice.

**Comment by renber** [comment]
Have you configured seafile's domain name in [ccnet.conf](https://manual.seafile.com/config/ccnet-conf.html? SERVICE_URL has to be set to the "publicly" visible address of the server in order for the share links to be correct (i.e. 192.168.56.100:8000).
I suppose 192.168.122.1 is the internal IP VirtualBox's dhcp assigns to the virtual machine.

**Comment by uPloraX** [comment]
Thanks for the quick reply, that worked out flawless.
